phrase:
  project_id: 3e43b3f90cf19e83c7d85652df5766ca
  file_format: strings
  pull:
    targets:
      - file: ./ui/src/main/res/values/strings.xml
        params:
          locale_id: b220db5757be359631c55ec54fb65ac6
          tags: "sdk"
          encoding: "UTF-8"
          file_format: xml
          include_empty_translations: false
          format_options:
            convert_placeholder: true
            escape_linebreaks: true
      - file: ./ui/src/main/res/values-<locale_name>/strings.xml
        params:
          tags: "sdk"
          encoding: "UTF-8"
          file_format: xml
          include_empty_translations: false
          format_options:
            convert_placeholder: true
            escape_linebreaks: true
      - file: ./ui-toolkit/src/debug/res/values/strings.xml
        params:
          locale_id: b220db5757be359631c55ec54fb65ac6
          tags: "Sample"
          encoding: "UTF-8"
          file_format: xml
          include_empty_translations: false
          format_options:
            convert_placeholder: true
            escape_linebreaks: true
      - file: ./ui-toolkit/src/main/res/values/strings.xml
        params:
          locale_id: b220db5757be359631c55ec54fb65ac6
          tags: "Onboarding"
          encoding: "UTF-8"
          file_format: xml
          include_empty_translations: false
          format_options:
            convert_placeholder: true
            escape_linebreaks: true
      - file: ./ui-toolkit/src/main/res/values-<locale_name>/strings.xml
        params:
          tags: "Onboarding"
          encoding: "UTF-8"
          file_format: xml
          include_empty_translations: false
          format_options:
            convert_placeholder: true
            escape_linebreaks: true
      - file: ./kotlin-sample/src/main/res/values/strings.xml
        params:
          locale_id: b220db5757be359631c55ec54fb65ac6
          tags: "Sample"
          encoding: "UTF-8"
          file_format: xml
          include_empty_translations: false
          format_options:
            convert_placeholder: true
            escape_linebreaks: true
      - file: ./kotlin-sample/src/main/res/values-<locale_name>/strings.xml
        params:
          tags: "Sample"
          encoding: "UTF-8"
          file_format: xml
          include_empty_translations: false
          format_options:
            convert_placeholder: true
            escape_linebreaks: true