# Configuration for Android projects: https://help.phrase.com/help/examples
phrase:
  file_format: xml
  pull:
    targets:
      # ui module
      - file: ./ui/src/main/res/values/strings.xml
        project_id: &id_core 3e43b3f90cf19e83c7d85652df5766ca
        params: &defaults
          locale_id: b220db5757be359631c55ec54fb65ac6 # en-US
          include_empty_translations: true
          format_options:
            convert_placeholder: true
            escape_linebreaks: true
      - file: ./ui/src/main/res/values-de/strings.xml
        project_id: *id_core
        params:
          <<: *defaults
          locale_id: 512f99f8cd03c80affd16303fb5de9c2 # de
      - file: ./ui/src/main/res/values-fr/strings.xml
        project_id: *id_core
        params:
          <<: *defaults
          locale_id: edf0b29dd998221329199f185d360ae4 # fr
      - file: ./ui/src/main/res/values-fr-rCH/strings.xml
        project_id: *id_core
        params:
          <<: *defaults
          locale_id: fae2e092d1704da2ed88f3f56eb6f219 # fr-CH
      - file: ./ui/src/main/res/values-hu/strings.xml
        project_id: *id_core
        params:
          <<: *defaults
          locale_id: 8f797bd77008e27f6286531a5ad55f67 # hu
      - file: ./ui/src/main/res/values-it/strings.xml
        project_id: *id_core
        params:
          <<: *defaults
          locale_id: a4dea5c3e2c77e7c6ea344e69db63ed9 # it
      - file: ./ui/src/main/res/values-sk/strings.xml
        project_id: *id_core
        params:
          <<: *defaults
          locale_id: 9ee4c528e480d56878c98ee8bfbc521b # sk

      # ui-toolkit module
      - file: ./ui-toolkit/src/main/res/values/strings.xml
        project_id: *id_core
        params:
          <<: *defaults
          locale_id: b220db5757be359631c55ec54fb65ac6 # en-US
          tags: Onboarding,Shop,Scanner
      - file: ./ui-toolkit/src/main/res/values-de/strings.xml
        project_id: *id_core
        params:
          <<: *defaults
          locale_id: 512f99f8cd03c80affd16303fb5de9c2 # de
          tags: Onboarding,Shop,Scanner
      - file: ./ui-toolkit/src/main/res/values-fr/strings.xml
        project_id: *id_core
        params:
          <<: *defaults
          locale_id: edf0b29dd998221329199f185d360ae4 # fr
          tags: Onboarding,Shop,Scanner
      - file: ./ui-toolkit/src/main/res/values-fr-rCH/strings.xml
        project_id: *id_core
        params:
          <<: *defaults
          locale_id: fae2e092d1704da2ed88f3f56eb6f219 # fr-CH
          tags: Onboarding,Shop,Scanner
      - file: ./ui-toolkit/src/main/res/values-hu/strings.xml
        project_id: *id_core
        params:
          <<: *defaults
          locale_id: 8f797bd77008e27f6286531a5ad55f67 # hu
          tags: Onboarding,Shop,Scanner
      - file: ./ui-toolkit/src/main/res/values-it/strings.xml
        project_id: *id_core
        params:
          <<: *defaults
          locale_id: a4dea5c3e2c77e7c6ea344e69db63ed9 # it
          tags: Onboarding,Shop,Scanner
      - file: ./ui-toolkit/src/main/res/values-sk/strings.xml
        project_id: *id_core
        params:
          <<: *defaults
          locale_id: 9ee4c528e480d56878c98ee8bfbc521b # sk
          tags: Onboarding,Shop,Scanner

      # kotlin-sample module
      - file: ./kotlin-sample/src/main/res/values/strings.xml
        project_id: &id_sample 02f8f3eb9dabfb0aa81565e94a450a78
        params: &sample
          locale_id: 8a496aa8b2a5b608340772cdac21a04f # en-US
          fallback_locale_id: 8a496aa8b2a5b608340772cdac21a04f # en-US
          include_empty_translations: true
          format_options:
            convert_placeholder: true
            escape_linebreaks: true
      - file: ./kotlin-sample/src/main/res/values-de/strings.xml
        project_id: *id_sample
        params:
          <<: *sample
          locale_id: 13770d8e586ebda4408ab2c847520941 # de
      - file: ./kotlin-sample/src/main/res/values-fr/strings.xml
        project_id: *id_sample
        params:
          <<: *sample
          locale_id: 6745aa0eb2ceabbe5896d06693ce167a # fr
      - file: ./kotlin-sample/src/main/res/values-fr-rCH/strings.xml
        project_id: *id_sample
        params:
          <<: *sample
          locale_id: ab0af54393819090368225ef021ab08e # fr-CH
      - file: ./kotlin-sample/src/main/res/values-hu/strings.xml
        project_id: *id_sample
        params:
          <<: *sample
          locale_id: fc083051fda750bca9f1d46086e39d11 # hu
      - file: ./kotlin-sample/src/main/res/values-it/strings.xml
        project_id: *id_sample
        params:
          <<: *sample
          locale_id: 5eefa9c0b0961371fd9c771066c7f9e5 # it
      - file: ./kotlin-sample/src/main/res/values-sk/strings.xml
        project_id: *id_sample
        params:
          <<: *sample
          locale_id: 1edff90fbc4524afa8b3678650211fac # sk
