phrase:
  project_id: 3e43b3f90cf19e83c7d85652df5766ca
  file_format: xml
  pull:
    targets:
      # ui module
      - file: ./ui/src/main/res/values/strings.xml
        params: &defaults
          locale_id: b220db5757be359631c55ec54fb65ac6
          fallback_locale_id: b220db5757be359631c55ec54fb65ac6
          tags: SDK,Coupons
          include_empty_translations: true
          format_options:
            convert_placeholder: true
            escape_linebreaks: true
      - file: ./ui/src/main/res/values-de/strings.xml
        params:
          <<: *defaults
          locale_id: 512f99f8cd03c80affd16303fb5de9c2
      - file: ./ui/src/main/res/values-fr/strings.xml
        params:
          <<: *defaults
          locale_id: edf0b29dd998221329199f185d360ae4
      - file: ./ui/src/main/res/values-fr-rCH/strings.xml
        params:
          <<: *defaults
          locale_id: fae2e092d1704da2ed88f3f56eb6f219
      - file: ./ui/src/main/res/values-hu/strings.xml
        params:
          <<: *defaults
          locale_id: 8f797bd77008e27f6286531a5ad55f67
      - file: ./ui/src/main/res/values-it/strings.xml
        params:
          <<: *defaults
          locale_id: a4dea5c3e2c77e7c6ea344e69db63ed9
      - file: ./ui/src/main/res/values-sk/strings.xml
        params:
          <<: *defaults
          locale_id: 9ee4c528e480d56878c98ee8bfbc521b
       
      # ui-toolkit module
      - file: ./ui-toolkit/src/debug/res/values/strings.xml
        params:
          <<: *defaults
          locale_id: b220db5757be359631c55ec54fb65ac6
          tags: Sample
      - file: ./ui-toolkit/src/main/res/values/strings.xml
        params:
          <<: *defaults
          locale_id: b220db5757be359631c55ec54fb65ac6
          tags: Onboarding
      - file: ./ui-toolkit/src/main/res/values-de/strings.xml
        params:
          <<: *defaults
          locale_id: 512f99f8cd03c80affd16303fb5de9c2
          tags: Onboarding
      - file: ./ui-toolkit/src/main/res/values-fr/strings.xml
        params:
          <<: *defaults
          locale_id: edf0b29dd998221329199f185d360ae4
          tags: Onboarding
      - file: ./ui-toolkit/src/main/res/values-fr-rCH/strings.xml
        params:
          <<: *defaults
          locale_id: fae2e092d1704da2ed88f3f56eb6f219
          tags: Onboarding
      - file: ./ui-toolkit/src/main/res/values-hu/strings.xml
        params:
          <<: *defaults
          locale_id: 8f797bd77008e27f6286531a5ad55f67
          tags: Onboarding
      - file: ./ui-toolkit/src/main/res/values-it/strings.xml
        params:
          <<: *defaults
          locale_id: a4dea5c3e2c77e7c6ea344e69db63ed9
          tags: Onboarding
      - file: ./ui-toolkit/src/main/res/values-sk/strings.xml
        params:
          <<: *defaults
          locale_id: 9ee4c528e480d56878c98ee8bfbc521b
          tags: Onboarding
      # kotlin-sample module
      - file: ./kotlin-sample/src/main/res/values/strings.xml
        params:
          <<: *defaults
          locale_id: b220db5757be359631c55ec54fb65ac6
          tags: Sample
      - file: ./kotlin-sample/src/main/res/values-de/strings.xml
        params:
          <<: *defaults
          locale_id: 512f99f8cd03c80affd16303fb5de9c2
          tags: Sample
      - file: ./kotlin-sample/src/main/res/values-fr/strings.xml
        params:
          <<: *defaults
          locale_id: edf0b29dd998221329199f185d360ae4
          tags: Sample
      - file: ./kotlin-sample/src/main/res/values-fr-rCH/strings.xml
        params:
          <<: *defaults
          locale_id: fae2e092d1704da2ed88f3f56eb6f219
          tags: Sample
      - file: ./kotlin-sample/src/main/res/values-hu/strings.xml
        params:
          <<: *defaults
          locale_id: 8f797bd77008e27f6286531a5ad55f67
          tags: Sample
      - file: ./kotlin-sample/src/main/res/values-it/strings.xml
        params:
          <<: *defaults
          locale_id: a4dea5c3e2c77e7c6ea344e69db63ed9
          tags: Sample
      - file: ./kotlin-sample/src/main/res/values-sk/strings.xml
        params:
          <<: *defaults
          locale_id: 9ee4c528e480d56878c98ee8bfbc521b
          tags: Sample