package io.snabble.sdk.codes.gs1

/**
 * Class for defining gs1 application identifiers
 */
data class ApplicationIdentifier(
        val prefix: String,
        val description: String,
        val format: String,
        val name: String,
        val needsFNC1: Boolean,
        val regex: String
) {
    val contentLength: Int
        get() {
            predefinedLengths[twoDigitIdentifier]?.let {
                return it - prefix.length - 2
            }
            return 0
        }

    val twoDigitIdentifier: String
        get() {
            return prefix.substring(0, 2)
        }

    val additionalIdentifier: String?
        get() {
            return prefix.substring(2)
        }

    companion object {
        private val charset82 = "\u0021-\u0022\u0025-\u002F\u0030-\u0039\u003A-\u003F\u0041-\u005A\u005F\u0061-\u007A"
        private val charset39 = "\u0023\u002D\u002F\u0030-\u0039\u0041-\u005A"
        
        val predefinedLengths = mapOf(
            "00" to 20, "01" to 16, "02" to 16, "03" to 16, "04" to 18, "11" to 8, "12" to 8, "13" to 8, "14" to 8,
            "15" to 8, "16" to 8, "17" to 8, "18" to 8, "19" to 8, "20" to 4, "31" to 10, "32" to 10, "33" to 10,
            "34" to 10, "35" to 10, "36" to 10, "41" to 16
        )

        val allIdentifiers = listOf(
                ApplicationIdentifier("00", "Serial Shipping Container Code (SSCC)", "N2+N18", "SSCC", false, "00(\\d{18})"),
                ApplicationIdentifier("01", "Global Trade Item Number (GTIN)", "N2+N14", "GTIN", false, "01(\\d{14})"),
                ApplicationIdentifier("02", "GTIN of contained trade items", "N2+N14", "CONTENT", false, "02(\\d{14})"),
                ApplicationIdentifier("10", "Batch or lot number", "N2+X..20", "BATCH/LOT", true, "10([$charset82]{0,20})"),
                ApplicationIdentifier("11", "Production date (YYMMDD)", "N2+N6", "PROD DATE", false, "11(\\d{6})"),
                ApplicationIdentifier("12", "Due date (YYMMDD)", "N2+N6", "DUE DATE", false, "12(\\d{6})"),
                ApplicationIdentifier("13", "Packaging date (YYMMDD)", "N2+N6", "PACK DATE", false, "13(\\d{6})"),
                ApplicationIdentifier("15", "Best before date (YYMMDD)", "N2+N6", "BEST BEFORE or BEST BY", false, "15(\\d{6})"),
                ApplicationIdentifier("16", "Sell by date (YYMMDD)", "N2+N6", "SELL BY", false, "16(\\d{6})"),
                ApplicationIdentifier("17", "Expiration date (YYMMDD)", "N2+N6", "USE BY OR EXPIRY", false, "17(\\d{6})"),
                ApplicationIdentifier("20", "Internal product variant", "N2+N2", "VARIANT", false, "20(\\d{2})"),
                ApplicationIdentifier("21", "Serial number", "N2+X..20", "SERIAL", true, "21([$charset82]{0,20})"),
                ApplicationIdentifier("22", "Consumer product variant", "N2+X..20", "CPV", true, "22([$charset82]{0,20})"),
                ApplicationIdentifier("235", "Third Party Controlled, Serialised Extension of GTIN (TPX)", "N3+X..28", "TPX", true, "235([$charset82]{0,28})"),
                ApplicationIdentifier("240", "Additional product identification assigned by the manufacturer", "N3+X..30", "ADDITIONAL ID", true, "240([$charset82]{0,30})"),
                ApplicationIdentifier("241", "Customer part number", "N3+X..30", "CUST. PART NO.", true, "241([$charset82]{0,30})"),
                ApplicationIdentifier("242", "Made-to-Order variation number", "N3+N..6", "MTO VARIANT", true, "242(\\d{0,6})"),
                ApplicationIdentifier("243", "Packaging component number", "N3+X..20", "PCN", true, "243([$charset82]{0,20})"),
                ApplicationIdentifier("250", "Secondary serial number", "N3+X..30", "SECONDARY SERIAL", true, "250([$charset82]{0,30})"),
                ApplicationIdentifier("251", "Reference to source entity", "N3+X..30", "REF. TO SOURCE", true, "251([$charset82]{0,30})"),
                ApplicationIdentifier("253", "Global Document Type Identifier (GDTI)", "N3+N13+X..17", "GDTI", true, "253(\\d{13})([$charset82]{0,17})"),
                ApplicationIdentifier("254", "GLN extension component", "N3+X..20", "GLN EXTENSION COMPONENT", true, "254([$charset82]{0,20})"),
                ApplicationIdentifier("255", "Global Coupon Number (GCN)", "N3+N13+N..12", "GCN", true, "255(\\d{13})(\\d{0,12})"),
                ApplicationIdentifier("30", "Variable count of items (variable measure trade item)", "N2+N..8", "VAR. COUNT", true, "30(\\d{0,8})"),
                ApplicationIdentifier("3100", "Net weight, kilograms (variable measure trade item)", "N4+N6", "NET WEIGHT (kg)", false, "3100(\\d{6})"),
                ApplicationIdentifier("3101", "Net weight, kilograms (variable measure trade item)", "N4+N6", "NET WEIGHT (kg)", false, "3101(\\d{6})"),
                ApplicationIdentifier("3102", "Net weight, kilograms (variable measure trade item)", "N4+N6", "NET WEIGHT (kg)", false, "3102(\\d{6})"),
                ApplicationIdentifier("3103", "Net weight, kilograms (variable measure trade item)", "N4+N6", "NET WEIGHT (kg)", false, "3103(\\d{6})"),
                ApplicationIdentifier("3104", "Net weight, kilograms (variable measure trade item)", "N4+N6", "NET WEIGHT (kg)", false, "3104(\\d{6})"),
                ApplicationIdentifier("3105", "Net weight, kilograms (variable measure trade item)", "N4+N6", "NET WEIGHT (kg)", false, "3105(\\d{6})"),
                ApplicationIdentifier("3110", "Length or first dimension, metres (variable measure trade item)", "N4+N6", "LENGTH (m)", false, "3110(\\d{6})"),
                ApplicationIdentifier("3111", "Length or first dimension, metres (variable measure trade item)", "N4+N6", "LENGTH (m)", false, "3111(\\d{6})"),
                ApplicationIdentifier("3112", "Length or first dimension, metres (variable measure trade item)", "N4+N6", "LENGTH (m)", false, "3112(\\d{6})"),
                ApplicationIdentifier("3113", "Length or first dimension, metres (variable measure trade item)", "N4+N6", "LENGTH (m)", false, "3113(\\d{6})"),
                ApplicationIdentifier("3114", "Length or first dimension, metres (variable measure trade item)", "N4+N6", "LENGTH (m)", false, "3114(\\d{6})"),
                ApplicationIdentifier("3115", "Length or first dimension, metres (variable measure trade item)", "N4+N6", "LENGTH (m)", false, "3115(\\d{6})"),
                ApplicationIdentifier("3120", "Width, diameter, or second dimension, metres (variable measure trade item)", "N4+N6", "WIDTH (m)", false, "3120(\\d{6})"),
                ApplicationIdentifier("3121", "Width, diameter, or second dimension, metres (variable measure trade item)", "N4+N6", "WIDTH (m)", false, "3121(\\d{6})"),
                ApplicationIdentifier("3122", "Width, diameter, or second dimension, metres (variable measure trade item)", "N4+N6", "WIDTH (m)", false, "3122(\\d{6})"),
                ApplicationIdentifier("3123", "Width, diameter, or second dimension, metres (variable measure trade item)", "N4+N6", "WIDTH (m)", false, "3123(\\d{6})"),
                ApplicationIdentifier("3124", "Width, diameter, or second dimension, metres (variable measure trade item)", "N4+N6", "WIDTH (m)", false, "3124(\\d{6})"),
                ApplicationIdentifier("3125", "Width, diameter, or second dimension, metres (variable measure trade item)", "N4+N6", "WIDTH (m)", false, "3125(\\d{6})"),
                ApplicationIdentifier("3130", "Depth, thickness, height, or third dimension, metres (variable measure trade item)", "N4+N6", "HEIGHT (m)", false, "3130(\\d{6})"),
                ApplicationIdentifier("3131", "Depth, thickness, height, or third dimension, metres (variable measure trade item)", "N4+N6", "HEIGHT (m)", false, "3131(\\d{6})"),
                ApplicationIdentifier("3132", "Depth, thickness, height, or third dimension, metres (variable measure trade item)", "N4+N6", "HEIGHT (m)", false, "3132(\\d{6})"),
                ApplicationIdentifier("3133", "Depth, thickness, height, or third dimension, metres (variable measure trade item)", "N4+N6", "HEIGHT (m)", false, "3133(\\d{6})"),
                ApplicationIdentifier("3134", "Depth, thickness, height, or third dimension, metres (variable measure trade item)", "N4+N6", "HEIGHT (m)", false, "3134(\\d{6})"),
                ApplicationIdentifier("3135", "Depth, thickness, height, or third dimension, metres (variable measure trade item)", "N4+N6", "HEIGHT (m)", false, "3135(\\d{6})"),
                ApplicationIdentifier("3140", "Area, square metres (variable measure trade item)", "N4+N6", "AREA (m2)", false, "3140(\\d{6})"),
                ApplicationIdentifier("3141", "Area, square metres (variable measure trade item)", "N4+N6", "AREA (m2)", false, "3141(\\d{6})"),
                ApplicationIdentifier("3142", "Area, square metres (variable measure trade item)", "N4+N6", "AREA (m2)", false, "3142(\\d{6})"),
                ApplicationIdentifier("3143", "Area, square metres (variable measure trade item)", "N4+N6", "AREA (m2)", false, "3143(\\d{6})"),
                ApplicationIdentifier("3144", "Area, square metres (variable measure trade item)", "N4+N6", "AREA (m2)", false, "3144(\\d{6})"),
                ApplicationIdentifier("3145", "Area, square metres (variable measure trade item)", "N4+N6", "AREA (m2)", false, "3145(\\d{6})"),
                ApplicationIdentifier("3150", "Net volume, litres (variable measure trade item)", "N4+N6", "NET VOLUME (l)", false, "3150(\\d{6})"),
                ApplicationIdentifier("3151", "Net volume, litres (variable measure trade item)", "N4+N6", "NET VOLUME (l)", false, "3151(\\d{6})"),
                ApplicationIdentifier("3152", "Net volume, litres (variable measure trade item)", "N4+N6", "NET VOLUME (l)", false, "3152(\\d{6})"),
                ApplicationIdentifier("3153", "Net volume, litres (variable measure trade item)", "N4+N6", "NET VOLUME (l)", false, "3153(\\d{6})"),
                ApplicationIdentifier("3154", "Net volume, litres (variable measure trade item)", "N4+N6", "NET VOLUME (l)", false, "3154(\\d{6})"),
                ApplicationIdentifier("3155", "Net volume, litres (variable measure trade item)", "N4+N6", "NET VOLUME (l)", false, "3155(\\d{6})"),
                ApplicationIdentifier("3160", "Net volume, cubic metres (variable measure trade item)", "N4+N6", "NET VOLUME (m3)", false, "3160(\\d{6})"),
                ApplicationIdentifier("3161", "Net volume, cubic metres (variable measure trade item)", "N4+N6", "NET VOLUME (m3)", false, "3161(\\d{6})"),
                ApplicationIdentifier("3162", "Net volume, cubic metres (variable measure trade item)", "N4+N6", "NET VOLUME (m3)", false, "3162(\\d{6})"),
                ApplicationIdentifier("3163", "Net volume, cubic metres (variable measure trade item)", "N4+N6", "NET VOLUME (m3)", false, "3163(\\d{6})"),
                ApplicationIdentifier("3164", "Net volume, cubic metres (variable measure trade item)", "N4+N6", "NET VOLUME (m3)", false, "3164(\\d{6})"),
                ApplicationIdentifier("3165", "Net volume, cubic metres (variable measure trade item)", "N4+N6", "NET VOLUME (m3)", false, "3165(\\d{6})"),
                ApplicationIdentifier("3200", "Net weight, pounds (variable measure trade item)", "N4+N6", "NET WEIGHT (lb)", false, "3200(\\d{6})"),
                ApplicationIdentifier("3201", "Net weight, pounds (variable measure trade item)", "N4+N6", "NET WEIGHT (lb)", false, "3201(\\d{6})"),
                ApplicationIdentifier("3202", "Net weight, pounds (variable measure trade item)", "N4+N6", "NET WEIGHT (lb)", false, "3202(\\d{6})"),
                ApplicationIdentifier("3203", "Net weight, pounds (variable measure trade item)", "N4+N6", "NET WEIGHT (lb)", false, "3203(\\d{6})"),
                ApplicationIdentifier("3204", "Net weight, pounds (variable measure trade item)", "N4+N6", "NET WEIGHT (lb)", false, "3204(\\d{6})"),
                ApplicationIdentifier("3205", "Net weight, pounds (variable measure trade item)", "N4+N6", "NET WEIGHT (lb)", false, "3205(\\d{6})"),
                ApplicationIdentifier("3210", "Length or first dimension, inches (variable measure trade item)", "N4+N6", "LENGTH (in)", false, "3210(\\d{6})"),
                ApplicationIdentifier("3211", "Length or first dimension, inches (variable measure trade item)", "N4+N6", "LENGTH (in)", false, "3211(\\d{6})"),
                ApplicationIdentifier("3212", "Length or first dimension, inches (variable measure trade item)", "N4+N6", "LENGTH (in)", false, "3212(\\d{6})"),
                ApplicationIdentifier("3213", "Length or first dimension, inches (variable measure trade item)", "N4+N6", "LENGTH (in)", false, "3213(\\d{6})"),
                ApplicationIdentifier("3214", "Length or first dimension, inches (variable measure trade item)", "N4+N6", "LENGTH (in)", false, "3214(\\d{6})"),
                ApplicationIdentifier("3215", "Length or first dimension, inches (variable measure trade item)", "N4+N6", "LENGTH (in)", false, "3215(\\d{6})"),
                ApplicationIdentifier("3220", "Length or first dimension, feet (variable measure trade item)", "N4+N6", "LENGTH (ft)", false, "3220(\\d{6})"),
                ApplicationIdentifier("3221", "Length or first dimension, feet (variable measure trade item)", "N4+N6", "LENGTH (ft)", false, "3221(\\d{6})"),
                ApplicationIdentifier("3222", "Length or first dimension, feet (variable measure trade item)", "N4+N6", "LENGTH (ft)", false, "3222(\\d{6})"),
                ApplicationIdentifier("3223", "Length or first dimension, feet (variable measure trade item)", "N4+N6", "LENGTH (ft)", false, "3223(\\d{6})"),
                ApplicationIdentifier("3224", "Length or first dimension, feet (variable measure trade item)", "N4+N6", "LENGTH (ft)", false, "3224(\\d{6})"),
                ApplicationIdentifier("3225", "Length or first dimension, feet (variable measure trade item)", "N4+N6", "LENGTH (ft)", false, "3225(\\d{6})"),
                ApplicationIdentifier("3230", "Length or first dimension, yards (variable measure trade item)", "N4+N6", "LENGTH (yd)", false, "3230(\\d{6})"),
                ApplicationIdentifier("3231", "Length or first dimension, yards (variable measure trade item)", "N4+N6", "LENGTH (yd)", false, "3231(\\d{6})"),
                ApplicationIdentifier("3232", "Length or first dimension, yards (variable measure trade item)", "N4+N6", "LENGTH (yd)", false, "3232(\\d{6})"),
                ApplicationIdentifier("3233", "Length or first dimension, yards (variable measure trade item)", "N4+N6", "LENGTH (yd)", false, "3233(\\d{6})"),
                ApplicationIdentifier("3234", "Length or first dimension, yards (variable measure trade item)", "N4+N6", "LENGTH (yd)", false, "3234(\\d{6})"),
                ApplicationIdentifier("3235", "Length or first dimension, yards (variable measure trade item)", "N4+N6", "LENGTH (yd)", false, "3235(\\d{6})"),
                ApplicationIdentifier("3240", "Width, diameter, or second dimension, inches (variable measure trade item)", "N4+N6", "WIDTH (in)", false, "3240(\\d{6})"),
                ApplicationIdentifier("3241", "Width, diameter, or second dimension, inches (variable measure trade item)", "N4+N6", "WIDTH (in)", false, "3241(\\d{6})"),
                ApplicationIdentifier("3242", "Width, diameter, or second dimension, inches (variable measure trade item)", "N4+N6", "WIDTH (in)", false, "3242(\\d{6})"),
                ApplicationIdentifier("3243", "Width, diameter, or second dimension, inches (variable measure trade item)", "N4+N6", "WIDTH (in)", false, "3243(\\d{6})"),
                ApplicationIdentifier("3244", "Width, diameter, or second dimension, inches (variable measure trade item)", "N4+N6", "WIDTH (in)", false, "3244(\\d{6})"),
                ApplicationIdentifier("3245", "Width, diameter, or second dimension, inches (variable measure trade item)", "N4+N6", "WIDTH (in)", false, "3245(\\d{6})"),
                ApplicationIdentifier("3250", "Width, diameter, or second dimension, feet (variable measure trade item)", "N4+N6", "WIDTH (ft)", false, "3250(\\d{6})"),
                ApplicationIdentifier("3251", "Width, diameter, or second dimension, feet (variable measure trade item)", "N4+N6", "WIDTH (ft)", false, "3251(\\d{6})"),
                ApplicationIdentifier("3252", "Width, diameter, or second dimension, feet (variable measure trade item)", "N4+N6", "WIDTH (ft)", false, "3252(\\d{6})"),
                ApplicationIdentifier("3253", "Width, diameter, or second dimension, feet (variable measure trade item)", "N4+N6", "WIDTH (ft)", false, "3253(\\d{6})"),
                ApplicationIdentifier("3254", "Width, diameter, or second dimension, feet (variable measure trade item)", "N4+N6", "WIDTH (ft)", false, "3254(\\d{6})"),
                ApplicationIdentifier("3255", "Width, diameter, or second dimension, feet (variable measure trade item)", "N4+N6", "WIDTH (ft)", false, "3255(\\d{6})"),
                ApplicationIdentifier("3260", "Width, diameter, or second dimension, yards (variable measure trade item)", "N4+N6", "WIDTH (yd)", false, "3260(\\d{6})"),
                ApplicationIdentifier("3261", "Width, diameter, or second dimension, yards (variable measure trade item)", "N4+N6", "WIDTH (yd)", false, "3261(\\d{6})"),
                ApplicationIdentifier("3262", "Width, diameter, or second dimension, yards (variable measure trade item)", "N4+N6", "WIDTH (yd)", false, "3262(\\d{6})"),
                ApplicationIdentifier("3263", "Width, diameter, or second dimension, yards (variable measure trade item)", "N4+N6", "WIDTH (yd)", false, "3263(\\d{6})"),
                ApplicationIdentifier("3264", "Width, diameter, or second dimension, yards (variable measure trade item)", "N4+N6", "WIDTH (yd)", false, "3264(\\d{6})"),
                ApplicationIdentifier("3265", "Width, diameter, or second dimension, yards (variable measure trade item)", "N4+N6", "WIDTH (yd)", false, "3265(\\d{6})"),
                ApplicationIdentifier("3270", "Depth, thickness, height, or third dimension, inches (variable measure trade item)", "N4+N6", "HEIGHT (in)", false, "3270(\\d{6})"),
                ApplicationIdentifier("3271", "Depth, thickness, height, or third dimension, inches (variable measure trade item)", "N4+N6", "HEIGHT (in)", false, "3271(\\d{6})"),
                ApplicationIdentifier("3272", "Depth, thickness, height, or third dimension, inches (variable measure trade item)", "N4+N6", "HEIGHT (in)", false, "3272(\\d{6})"),
                ApplicationIdentifier("3273", "Depth, thickness, height, or third dimension, inches (variable measure trade item)", "N4+N6", "HEIGHT (in)", false, "3273(\\d{6})"),
                ApplicationIdentifier("3274", "Depth, thickness, height, or third dimension, inches (variable measure trade item)", "N4+N6", "HEIGHT (in)", false, "3274(\\d{6})"),
                ApplicationIdentifier("3275", "Depth, thickness, height, or third dimension, inches (variable measure trade item)", "N4+N6", "HEIGHT (in)", false, "3275(\\d{6})"),
                ApplicationIdentifier("3280", "Depth, thickness, height, or third dimension, feet (variable measure trade item)", "N4+N6", "HEIGHT (ft)", false, "3280(\\d{6})"),
                ApplicationIdentifier("3281", "Depth, thickness, height, or third dimension, feet (variable measure trade item)", "N4+N6", "HEIGHT (ft)", false, "3281(\\d{6})"),
                ApplicationIdentifier("3282", "Depth, thickness, height, or third dimension, feet (variable measure trade item)", "N4+N6", "HEIGHT (ft)", false, "3282(\\d{6})"),
                ApplicationIdentifier("3283", "Depth, thickness, height, or third dimension, feet (variable measure trade item)", "N4+N6", "HEIGHT (ft)", false, "3283(\\d{6})"),
                ApplicationIdentifier("3284", "Depth, thickness, height, or third dimension, feet (variable measure trade item)", "N4+N6", "HEIGHT (ft)", false, "3284(\\d{6})"),
                ApplicationIdentifier("3285", "Depth, thickness, height, or third dimension, feet (variable measure trade item)", "N4+N6", "HEIGHT (ft)", false, "3285(\\d{6})"),
                ApplicationIdentifier("3290", "Depth, thickness, height, or third dimension, yards (variable measure trade item)", "N4+N6", "HEIGHT (yd)", false, "3290(\\d{6})"),
                ApplicationIdentifier("3291", "Depth, thickness, height, or third dimension, yards (variable measure trade item)", "N4+N6", "HEIGHT (yd)", false, "3291(\\d{6})"),
                ApplicationIdentifier("3292", "Depth, thickness, height, or third dimension, yards (variable measure trade item)", "N4+N6", "HEIGHT (yd)", false, "3292(\\d{6})"),
                ApplicationIdentifier("3293", "Depth, thickness, height, or third dimension, yards (variable measure trade item)", "N4+N6", "HEIGHT (yd)", false, "3293(\\d{6})"),
                ApplicationIdentifier("3294", "Depth, thickness, height, or third dimension, yards (variable measure trade item)", "N4+N6", "HEIGHT (yd)", false, "3294(\\d{6})"),
                ApplicationIdentifier("3295", "Depth, thickness, height, or third dimension, yards (variable measure trade item)", "N4+N6", "HEIGHT (yd)", false, "3295(\\d{6})"),
                ApplicationIdentifier("3300", "Logistic weight, kilograms", "N4+N6", "GROSS WEIGHT (kg)", false, "3300(\\d{6})"),
                ApplicationIdentifier("3301", "Logistic weight, kilograms", "N4+N6", "GROSS WEIGHT (kg)", false, "3301(\\d{6})"),
                ApplicationIdentifier("3302", "Logistic weight, kilograms", "N4+N6", "GROSS WEIGHT (kg)", false, "3302(\\d{6})"),
                ApplicationIdentifier("3303", "Logistic weight, kilograms", "N4+N6", "GROSS WEIGHT (kg)", false, "3303(\\d{6})"),
                ApplicationIdentifier("3304", "Logistic weight, kilograms", "N4+N6", "GROSS WEIGHT (kg)", false, "3304(\\d{6})"),
                ApplicationIdentifier("3305", "Logistic weight, kilograms", "N4+N6", "GROSS WEIGHT (kg)", false, "3305(\\d{6})"),
                ApplicationIdentifier("3310", "Length or first dimension, metres", "N4+N6", "LENGTH (m), log", false, "3310(\\d{6})"),
                ApplicationIdentifier("3311", "Length or first dimension, metres", "N4+N6", "LENGTH (m), log", false, "3311(\\d{6})"),
                ApplicationIdentifier("3312", "Length or first dimension, metres", "N4+N6", "LENGTH (m), log", false, "3312(\\d{6})"),
                ApplicationIdentifier("3313", "Length or first dimension, metres", "N4+N6", "LENGTH (m), log", false, "3313(\\d{6})"),
                ApplicationIdentifier("3314", "Length or first dimension, metres", "N4+N6", "LENGTH (m), log", false, "3314(\\d{6})"),
                ApplicationIdentifier("3315", "Length or first dimension, metres", "N4+N6", "LENGTH (m), log", false, "3315(\\d{6})"),
                ApplicationIdentifier("3320", "Width, diameter, or second dimension, metres", "N4+N6", "WIDTH (m), log", false, "3320(\\d{6})"),
                ApplicationIdentifier("3321", "Width, diameter, or second dimension, metres", "N4+N6", "WIDTH (m), log", false, "3321(\\d{6})"),
                ApplicationIdentifier("3322", "Width, diameter, or second dimension, metres", "N4+N6", "WIDTH (m), log", false, "3322(\\d{6})"),
                ApplicationIdentifier("3323", "Width, diameter, or second dimension, metres", "N4+N6", "WIDTH (m), log", false, "3323(\\d{6})"),
                ApplicationIdentifier("3324", "Width, diameter, or second dimension, metres", "N4+N6", "WIDTH (m), log", false, "3324(\\d{6})"),
                ApplicationIdentifier("3325", "Width, diameter, or second dimension, metres", "N4+N6", "WIDTH (m), log", false, "3325(\\d{6})"),
                ApplicationIdentifier("3330", "Depth, thickness, height, or third dimension, metres", "N4+N6", "HEIGHT (m), log", false, "3330(\\d{6})"),
                ApplicationIdentifier("3331", "Depth, thickness, height, or third dimension, metres", "N4+N6", "HEIGHT (m), log", false, "3331(\\d{6})"),
                ApplicationIdentifier("3332", "Depth, thickness, height, or third dimension, metres", "N4+N6", "HEIGHT (m), log", false, "3332(\\d{6})"),
                ApplicationIdentifier("3333", "Depth, thickness, height, or third dimension, metres", "N4+N6", "HEIGHT (m), log", false, "3333(\\d{6})"),
                ApplicationIdentifier("3334", "Depth, thickness, height, or third dimension, metres", "N4+N6", "HEIGHT (m), log", false, "3334(\\d{6})"),
                ApplicationIdentifier("3335", "Depth, thickness, height, or third dimension, metres", "N4+N6", "HEIGHT (m), log", false, "3335(\\d{6})"),
                ApplicationIdentifier("3340", "Area, square metres", "N4+N6", "AREA (m2), log", false, "3340(\\d{6})"),
                ApplicationIdentifier("3341", "Area, square metres", "N4+N6", "AREA (m2), log", false, "3341(\\d{6})"),
                ApplicationIdentifier("3342", "Area, square metres", "N4+N6", "AREA (m2), log", false, "3342(\\d{6})"),
                ApplicationIdentifier("3343", "Area, square metres", "N4+N6", "AREA (m2), log", false, "3343(\\d{6})"),
                ApplicationIdentifier("3344", "Area, square metres", "N4+N6", "AREA (m2), log", false, "3344(\\d{6})"),
                ApplicationIdentifier("3345", "Area, square metres", "N4+N6", "AREA (m2), log", false, "3345(\\d{6})"),
                ApplicationIdentifier("3350", "Logistic volume, litres", "N4+N6", "VOLUME (l), log", false, "3350(\\d{6})"),
                ApplicationIdentifier("3351", "Logistic volume, litres", "N4+N6", "VOLUME (l), log", false, "3351(\\d{6})"),
                ApplicationIdentifier("3352", "Logistic volume, litres", "N4+N6", "VOLUME (l), log", false, "3352(\\d{6})"),
                ApplicationIdentifier("3353", "Logistic volume, litres", "N4+N6", "VOLUME (l), log", false, "3353(\\d{6})"),
                ApplicationIdentifier("3354", "Logistic volume, litres", "N4+N6", "VOLUME (l), log", false, "3354(\\d{6})"),
                ApplicationIdentifier("3355", "Logistic volume, litres", "N4+N6", "VOLUME (l), log", false, "3355(\\d{6})"),
                ApplicationIdentifier("3360", "Logistic volume, cubic metres", "N4+N6", "VOLUME (m3), log", false, "3360(\\d{6})"),
                ApplicationIdentifier("3361", "Logistic volume, cubic metres", "N4+N6", "VOLUME (m3), log", false, "3361(\\d{6})"),
                ApplicationIdentifier("3362", "Logistic volume, cubic metres", "N4+N6", "VOLUME (m3), log", false, "3362(\\d{6})"),
                ApplicationIdentifier("3363", "Logistic volume, cubic metres", "N4+N6", "VOLUME (m3), log", false, "3363(\\d{6})"),
                ApplicationIdentifier("3364", "Logistic volume, cubic metres", "N4+N6", "VOLUME (m3), log", false, "3364(\\d{6})"),
                ApplicationIdentifier("3365", "Logistic volume, cubic metres", "N4+N6", "VOLUME (m3), log", false, "3365(\\d{6})"),
                ApplicationIdentifier("3370", "Kilograms per square metre", "N4+N6", "KG PER m2", false, "3370(\\d{6})"),
                ApplicationIdentifier("3371", "Kilograms per square metre", "N4+N6", "KG PER m2", false, "3371(\\d{6})"),
                ApplicationIdentifier("3372", "Kilograms per square metre", "N4+N6", "KG PER m2", false, "3372(\\d{6})"),
                ApplicationIdentifier("3373", "Kilograms per square metre", "N4+N6", "KG PER m2", false, "3373(\\d{6})"),
                ApplicationIdentifier("3374", "Kilograms per square metre", "N4+N6", "KG PER m2", false, "3374(\\d{6})"),
                ApplicationIdentifier("3375", "Kilograms per square metre", "N4+N6", "KG PER m2", false, "3375(\\d{6})"),
                ApplicationIdentifier("3400", "Logistic weight, pounds", "N4+N6", "GROSS WEIGHT (lb)", false, "3400(\\d{6})"),
                ApplicationIdentifier("3401", "Logistic weight, pounds", "N4+N6", "GROSS WEIGHT (lb)", false, "3401(\\d{6})"),
                ApplicationIdentifier("3402", "Logistic weight, pounds", "N4+N6", "GROSS WEIGHT (lb)", false, "3402(\\d{6})"),
                ApplicationIdentifier("3403", "Logistic weight, pounds", "N4+N6", "GROSS WEIGHT (lb)", false, "3403(\\d{6})"),
                ApplicationIdentifier("3404", "Logistic weight, pounds", "N4+N6", "GROSS WEIGHT (lb)", false, "3404(\\d{6})"),
                ApplicationIdentifier("3405", "Logistic weight, pounds", "N4+N6", "GROSS WEIGHT (lb)", false, "3405(\\d{6})"),
                ApplicationIdentifier("3410", "Length or first dimension, inches", "N4+N6", "LENGTH (in), log", false, "3410(\\d{6})"),
                ApplicationIdentifier("3411", "Length or first dimension, inches", "N4+N6", "LENGTH (in), log", false, "3411(\\d{6})"),
                ApplicationIdentifier("3412", "Length or first dimension, inches", "N4+N6", "LENGTH (in), log", false, "3412(\\d{6})"),
                ApplicationIdentifier("3413", "Length or first dimension, inches", "N4+N6", "LENGTH (in), log", false, "3413(\\d{6})"),
                ApplicationIdentifier("3414", "Length or first dimension, inches", "N4+N6", "LENGTH (in), log", false, "3414(\\d{6})"),
                ApplicationIdentifier("3415", "Length or first dimension, inches", "N4+N6", "LENGTH (in), log", false, "3415(\\d{6})"),
                ApplicationIdentifier("3420", "Length or first dimension, feet", "N4+N6", "LENGTH (ft), log", false, "3420(\\d{6})"),
                ApplicationIdentifier("3421", "Length or first dimension, feet", "N4+N6", "LENGTH (ft), log", false, "3421(\\d{6})"),
                ApplicationIdentifier("3422", "Length or first dimension, feet", "N4+N6", "LENGTH (ft), log", false, "3422(\\d{6})"),
                ApplicationIdentifier("3423", "Length or first dimension, feet", "N4+N6", "LENGTH (ft), log", false, "3423(\\d{6})"),
                ApplicationIdentifier("3424", "Length or first dimension, feet", "N4+N6", "LENGTH (ft), log", false, "3424(\\d{6})"),
                ApplicationIdentifier("3425", "Length or first dimension, feet", "N4+N6", "LENGTH (ft), log", false, "3425(\\d{6})"),
                ApplicationIdentifier("3430", "Length or first dimension, yards", "N4+N6", "LENGTH (yd), log", false, "3430(\\d{6})"),
                ApplicationIdentifier("3431", "Length or first dimension, yards", "N4+N6", "LENGTH (yd), log", false, "3431(\\d{6})"),
                ApplicationIdentifier("3432", "Length or first dimension, yards", "N4+N6", "LENGTH (yd), log", false, "3432(\\d{6})"),
                ApplicationIdentifier("3433", "Length or first dimension, yards", "N4+N6", "LENGTH (yd), log", false, "3433(\\d{6})"),
                ApplicationIdentifier("3434", "Length or first dimension, yards", "N4+N6", "LENGTH (yd), log", false, "3434(\\d{6})"),
                ApplicationIdentifier("3435", "Length or first dimension, yards", "N4+N6", "LENGTH (yd), log", false, "3435(\\d{6})"),
                ApplicationIdentifier("3440", "Width, diameter, or second dimension, inches", "N4+N6", "WIDTH (in), log", false, "3440(\\d{6})"),
                ApplicationIdentifier("3441", "Width, diameter, or second dimension, inches", "N4+N6", "WIDTH (in), log", false, "3441(\\d{6})"),
                ApplicationIdentifier("3442", "Width, diameter, or second dimension, inches", "N4+N6", "WIDTH (in), log", false, "3442(\\d{6})"),
                ApplicationIdentifier("3443", "Width, diameter, or second dimension, inches", "N4+N6", "WIDTH (in), log", false, "3443(\\d{6})"),
                ApplicationIdentifier("3444", "Width, diameter, or second dimension, inches", "N4+N6", "WIDTH (in), log", false, "3444(\\d{6})"),
                ApplicationIdentifier("3445", "Width, diameter, or second dimension, inches", "N4+N6", "WIDTH (in), log", false, "3445(\\d{6})"),
                ApplicationIdentifier("3450", "Width, diameter, or second dimension, feet", "N4+N6", "WIDTH (ft), log", false, "3450(\\d{6})"),
                ApplicationIdentifier("3451", "Width, diameter, or second dimension, feet", "N4+N6", "WIDTH (ft), log", false, "3451(\\d{6})"),
                ApplicationIdentifier("3452", "Width, diameter, or second dimension, feet", "N4+N6", "WIDTH (ft), log", false, "3452(\\d{6})"),
                ApplicationIdentifier("3453", "Width, diameter, or second dimension, feet", "N4+N6", "WIDTH (ft), log", false, "3453(\\d{6})"),
                ApplicationIdentifier("3454", "Width, diameter, or second dimension, feet", "N4+N6", "WIDTH (ft), log", false, "3454(\\d{6})"),
                ApplicationIdentifier("3455", "Width, diameter, or second dimension, feet", "N4+N6", "WIDTH (ft), log", false, "3455(\\d{6})"),
                ApplicationIdentifier("3460", "Width, diameter, or second dimension, yard", "N4+N6", "WIDTH (yd), log", false, "3460(\\d{6})"),
                ApplicationIdentifier("3461", "Width, diameter, or second dimension, yard", "N4+N6", "WIDTH (yd), log", false, "3461(\\d{6})"),
                ApplicationIdentifier("3462", "Width, diameter, or second dimension, yard", "N4+N6", "WIDTH (yd), log", false, "3462(\\d{6})"),
                ApplicationIdentifier("3463", "Width, diameter, or second dimension, yard", "N4+N6", "WIDTH (yd), log", false, "3463(\\d{6})"),
                ApplicationIdentifier("3464", "Width, diameter, or second dimension, yard", "N4+N6", "WIDTH (yd), log", false, "3464(\\d{6})"),
                ApplicationIdentifier("3465", "Width, diameter, or second dimension, yard", "N4+N6", "WIDTH (yd), log", false, "3465(\\d{6})"),
                ApplicationIdentifier("3470", "Depth, thickness, height, or third dimension, inches", "N4+N6", "HEIGHT (in), log", false, "3470(\\d{6})"),
                ApplicationIdentifier("3471", "Depth, thickness, height, or third dimension, inches", "N4+N6", "HEIGHT (in), log", false, "3471(\\d{6})"),
                ApplicationIdentifier("3472", "Depth, thickness, height, or third dimension, inches", "N4+N6", "HEIGHT (in), log", false, "3472(\\d{6})"),
                ApplicationIdentifier("3473", "Depth, thickness, height, or third dimension, inches", "N4+N6", "HEIGHT (in), log", false, "3473(\\d{6})"),
                ApplicationIdentifier("3474", "Depth, thickness, height, or third dimension, inches", "N4+N6", "HEIGHT (in), log", false, "3474(\\d{6})"),
                ApplicationIdentifier("3475", "Depth, thickness, height, or third dimension, inches", "N4+N6", "HEIGHT (in), log", false, "3475(\\d{6})"),
                ApplicationIdentifier("3480", "Depth, thickness, height, or third dimension, feet", "N4+N6", "HEIGHT (ft), log", false, "3480(\\d{6})"),
                ApplicationIdentifier("3481", "Depth, thickness, height, or third dimension, feet", "N4+N6", "HEIGHT (ft), log", false, "3481(\\d{6})"),
                ApplicationIdentifier("3482", "Depth, thickness, height, or third dimension, feet", "N4+N6", "HEIGHT (ft), log", false, "3482(\\d{6})"),
                ApplicationIdentifier("3483", "Depth, thickness, height, or third dimension, feet", "N4+N6", "HEIGHT (ft), log", false, "3483(\\d{6})"),
                ApplicationIdentifier("3484", "Depth, thickness, height, or third dimension, feet", "N4+N6", "HEIGHT (ft), log", false, "3484(\\d{6})"),
                ApplicationIdentifier("3485", "Depth, thickness, height, or third dimension, feet", "N4+N6", "HEIGHT (ft), log", false, "3485(\\d{6})"),
                ApplicationIdentifier("3490", "Depth, thickness, height, or third dimension, yards", "N4+N6", "HEIGHT (yd), log", false, "3490(\\d{6})"),
                ApplicationIdentifier("3491", "Depth, thickness, height, or third dimension, yards", "N4+N6", "HEIGHT (yd), log", false, "3491(\\d{6})"),
                ApplicationIdentifier("3492", "Depth, thickness, height, or third dimension, yards", "N4+N6", "HEIGHT (yd), log", false, "3492(\\d{6})"),
                ApplicationIdentifier("3493", "Depth, thickness, height, or third dimension, yards", "N4+N6", "HEIGHT (yd), log", false, "3493(\\d{6})"),
                ApplicationIdentifier("3494", "Depth, thickness, height, or third dimension, yards", "N4+N6", "HEIGHT (yd), log", false, "3494(\\d{6})"),
                ApplicationIdentifier("3495", "Depth, thickness, height, or third dimension, yards", "N4+N6", "HEIGHT (yd), log", false, "3495(\\d{6})"),
                ApplicationIdentifier("3500", "Area, square inches (variable measure trade item)", "N4+N6", "AREA (in2)", false, "3500(\\d{6})"),
                ApplicationIdentifier("3501", "Area, square inches (variable measure trade item)", "N4+N6", "AREA (in2)", false, "3501(\\d{6})"),
                ApplicationIdentifier("3502", "Area, square inches (variable measure trade item)", "N4+N6", "AREA (in2)", false, "3502(\\d{6})"),
                ApplicationIdentifier("3503", "Area, square inches (variable measure trade item)", "N4+N6", "AREA (in2)", false, "3503(\\d{6})"),
                ApplicationIdentifier("3504", "Area, square inches (variable measure trade item)", "N4+N6", "AREA (in2)", false, "3504(\\d{6})"),
                ApplicationIdentifier("3505", "Area, square inches (variable measure trade item)", "N4+N6", "AREA (in2)", false, "3505(\\d{6})"),
                ApplicationIdentifier("3510", "Area, square feet (variable measure trade item)", "N4+N6", "AREA (ft2)", false, "3510(\\d{6})"),
                ApplicationIdentifier("3511", "Area, square feet (variable measure trade item)", "N4+N6", "AREA (ft2)", false, "3511(\\d{6})"),
                ApplicationIdentifier("3512", "Area, square feet (variable measure trade item)", "N4+N6", "AREA (ft2)", false, "3512(\\d{6})"),
                ApplicationIdentifier("3513", "Area, square feet (variable measure trade item)", "N4+N6", "AREA (ft2)", false, "3513(\\d{6})"),
                ApplicationIdentifier("3514", "Area, square feet (variable measure trade item)", "N4+N6", "AREA (ft2)", false, "3514(\\d{6})"),
                ApplicationIdentifier("3515", "Area, square feet (variable measure trade item)", "N4+N6", "AREA (ft2)", false, "3515(\\d{6})"),
                ApplicationIdentifier("3520", "Area, square yards (variable measure trade item)", "N4+N6", "AREA (yd2)", false, "3520(\\d{6})"),
                ApplicationIdentifier("3521", "Area, square yards (variable measure trade item)", "N4+N6", "AREA (yd2)", false, "3521(\\d{6})"),
                ApplicationIdentifier("3522", "Area, square yards (variable measure trade item)", "N4+N6", "AREA (yd2)", false, "3522(\\d{6})"),
                ApplicationIdentifier("3523", "Area, square yards (variable measure trade item)", "N4+N6", "AREA (yd2)", false, "3523(\\d{6})"),
                ApplicationIdentifier("3524", "Area, square yards (variable measure trade item)", "N4+N6", "AREA (yd2)", false, "3524(\\d{6})"),
                ApplicationIdentifier("3525", "Area, square yards (variable measure trade item)", "N4+N6", "AREA (yd2)", false, "3525(\\d{6})"),
                ApplicationIdentifier("3530", "Area, square inches", "N4+N6", "AREA (in2), log", false, "3530(\\d{6})"),
                ApplicationIdentifier("3531", "Area, square inches", "N4+N6", "AREA (in2), log", false, "3531(\\d{6})"),
                ApplicationIdentifier("3532", "Area, square inches", "N4+N6", "AREA (in2), log", false, "3532(\\d{6})"),
                ApplicationIdentifier("3533", "Area, square inches", "N4+N6", "AREA (in2), log", false, "3533(\\d{6})"),
                ApplicationIdentifier("3534", "Area, square inches", "N4+N6", "AREA (in2), log", false, "3534(\\d{6})"),
                ApplicationIdentifier("3535", "Area, square inches", "N4+N6", "AREA (in2), log", false, "3535(\\d{6})"),
                ApplicationIdentifier("3540", "Area, square feet", "N4+N6", "AREA (ft2), log", false, "3540(\\d{6})"),
                ApplicationIdentifier("3541", "Area, square feet", "N4+N6", "AREA (ft2), log", false, "3541(\\d{6})"),
                ApplicationIdentifier("3542", "Area, square feet", "N4+N6", "AREA (ft2), log", false, "3542(\\d{6})"),
                ApplicationIdentifier("3543", "Area, square feet", "N4+N6", "AREA (ft2), log", false, "3543(\\d{6})"),
                ApplicationIdentifier("3544", "Area, square feet", "N4+N6", "AREA (ft2), log", false, "3544(\\d{6})"),
                ApplicationIdentifier("3545", "Area, square feet", "N4+N6", "AREA (ft2), log", false, "3545(\\d{6})"),
                ApplicationIdentifier("3550", "Area, square yards", "N4+N6", "AREA (yd2), log", false, "3550(\\d{6})"),
                ApplicationIdentifier("3551", "Area, square yards", "N4+N6", "AREA (yd2), log", false, "3551(\\d{6})"),
                ApplicationIdentifier("3552", "Area, square yards", "N4+N6", "AREA (yd2), log", false, "3552(\\d{6})"),
                ApplicationIdentifier("3553", "Area, square yards", "N4+N6", "AREA (yd2), log", false, "3553(\\d{6})"),
                ApplicationIdentifier("3554", "Area, square yards", "N4+N6", "AREA (yd2), log", false, "3554(\\d{6})"),
                ApplicationIdentifier("3555", "Area, square yards", "N4+N6", "AREA (yd2), log", false, "3555(\\d{6})"),
                ApplicationIdentifier("3560", "Net weight, troy ounces (variable measure trade item)", "N4+N6", "NET WEIGHT (t oz)", false, "3560(\\d{6})"),
                ApplicationIdentifier("3561", "Net weight, troy ounces (variable measure trade item)", "N4+N6", "NET WEIGHT (t oz)", false, "3561(\\d{6})"),
                ApplicationIdentifier("3562", "Net weight, troy ounces (variable measure trade item)", "N4+N6", "NET WEIGHT (t oz)", false, "3562(\\d{6})"),
                ApplicationIdentifier("3563", "Net weight, troy ounces (variable measure trade item)", "N4+N6", "NET WEIGHT (t oz)", false, "3563(\\d{6})"),
                ApplicationIdentifier("3564", "Net weight, troy ounces (variable measure trade item)", "N4+N6", "NET WEIGHT (t oz)", false, "3564(\\d{6})"),
                ApplicationIdentifier("3565", "Net weight, troy ounces (variable measure trade item)", "N4+N6", "NET WEIGHT (t oz)", false, "3565(\\d{6})"),
                ApplicationIdentifier("3570", "Net weight (or volume), ounces (variable measure trade item)", "N4+N6", "NET VOLUME (oz)", false, "3570(\\d{6})"),
                ApplicationIdentifier("3571", "Net weight (or volume), ounces (variable measure trade item)", "N4+N6", "NET VOLUME (oz)", false, "3571(\\d{6})"),
                ApplicationIdentifier("3572", "Net weight (or volume), ounces (variable measure trade item)", "N4+N6", "NET VOLUME (oz)", false, "3572(\\d{6})"),
                ApplicationIdentifier("3573", "Net weight (or volume), ounces (variable measure trade item)", "N4+N6", "NET VOLUME (oz)", false, "3573(\\d{6})"),
                ApplicationIdentifier("3574", "Net weight (or volume), ounces (variable measure trade item)", "N4+N6", "NET VOLUME (oz)", false, "3574(\\d{6})"),
                ApplicationIdentifier("3575", "Net weight (or volume), ounces (variable measure trade item)", "N4+N6", "NET VOLUME (oz)", false, "3575(\\d{6})"),
                ApplicationIdentifier("3600", "Net volume, quarts (variable measure trade item)", "N4+N6", "NET VOLUME (qt)", false, "3600(\\d{6})"),
                ApplicationIdentifier("3601", "Net volume, quarts (variable measure trade item)", "N4+N6", "NET VOLUME (qt)", false, "3601(\\d{6})"),
                ApplicationIdentifier("3602", "Net volume, quarts (variable measure trade item)", "N4+N6", "NET VOLUME (qt)", false, "3602(\\d{6})"),
                ApplicationIdentifier("3603", "Net volume, quarts (variable measure trade item)", "N4+N6", "NET VOLUME (qt)", false, "3603(\\d{6})"),
                ApplicationIdentifier("3604", "Net volume, quarts (variable measure trade item)", "N4+N6", "NET VOLUME (qt)", false, "3604(\\d{6})"),
                ApplicationIdentifier("3605", "Net volume, quarts (variable measure trade item)", "N4+N6", "NET VOLUME (qt)", false, "3605(\\d{6})"),
                ApplicationIdentifier("3610", "Net volume, gallons U.S. (variable measure trade item)", "N4+N6", "NET VOLUME (gal.)", false, "3610(\\d{6})"),
                ApplicationIdentifier("3611", "Net volume, gallons U.S. (variable measure trade item)", "N4+N6", "NET VOLUME (gal.)", false, "3611(\\d{6})"),
                ApplicationIdentifier("3612", "Net volume, gallons U.S. (variable measure trade item)", "N4+N6", "NET VOLUME (gal.)", false, "3612(\\d{6})"),
                ApplicationIdentifier("3613", "Net volume, gallons U.S. (variable measure trade item)", "N4+N6", "NET VOLUME (gal.)", false, "3613(\\d{6})"),
                ApplicationIdentifier("3614", "Net volume, gallons U.S. (variable measure trade item)", "N4+N6", "NET VOLUME (gal.)", false, "3614(\\d{6})"),
                ApplicationIdentifier("3615", "Net volume, gallons U.S. (variable measure trade item)", "N4+N6", "NET VOLUME (gal.)", false, "3615(\\d{6})"),
                ApplicationIdentifier("3620", "Logistic volume, quarts", "N4+N6", "VOLUME (qt), log", false, "3620(\\d{6})"),
                ApplicationIdentifier("3621", "Logistic volume, quarts", "N4+N6", "VOLUME (qt), log", false, "3621(\\d{6})"),
                ApplicationIdentifier("3622", "Logistic volume, quarts", "N4+N6", "VOLUME (qt), log", false, "3622(\\d{6})"),
                ApplicationIdentifier("3623", "Logistic volume, quarts", "N4+N6", "VOLUME (qt), log", false, "3623(\\d{6})"),
                ApplicationIdentifier("3624", "Logistic volume, quarts", "N4+N6", "VOLUME (qt), log", false, "3624(\\d{6})"),
                ApplicationIdentifier("3625", "Logistic volume, quarts", "N4+N6", "VOLUME (qt), log", false, "3625(\\d{6})"),
                ApplicationIdentifier("3630", "Logistic volume, gallons U.S.", "N4+N6", "VOLUME (gal.), log", false, "3630(\\d{6})"),
                ApplicationIdentifier("3631", "Logistic volume, gallons U.S.", "N4+N6", "VOLUME (gal.), log", false, "3631(\\d{6})"),
                ApplicationIdentifier("3632", "Logistic volume, gallons U.S.", "N4+N6", "VOLUME (gal.), log", false, "3632(\\d{6})"),
                ApplicationIdentifier("3633", "Logistic volume, gallons U.S.", "N4+N6", "VOLUME (gal.), log", false, "3633(\\d{6})"),
                ApplicationIdentifier("3634", "Logistic volume, gallons U.S.", "N4+N6", "VOLUME (gal.), log", false, "3634(\\d{6})"),
                ApplicationIdentifier("3635", "Logistic volume, gallons U.S.", "N4+N6", "VOLUME (gal.), log", false, "3635(\\d{6})"),
                ApplicationIdentifier("3640", "Net volume, cubic inches (variable measure trade item)", "N4+N6", "VOLUME (in3)", false, "3640(\\d{6})"),
                ApplicationIdentifier("3641", "Net volume, cubic inches (variable measure trade item)", "N4+N6", "VOLUME (in3)", false, "3641(\\d{6})"),
                ApplicationIdentifier("3642", "Net volume, cubic inches (variable measure trade item)", "N4+N6", "VOLUME (in3)", false, "3642(\\d{6})"),
                ApplicationIdentifier("3643", "Net volume, cubic inches (variable measure trade item)", "N4+N6", "VOLUME (in3)", false, "3643(\\d{6})"),
                ApplicationIdentifier("3644", "Net volume, cubic inches (variable measure trade item)", "N4+N6", "VOLUME (in3)", false, "3644(\\d{6})"),
                ApplicationIdentifier("3645", "Net volume, cubic inches (variable measure trade item)", "N4+N6", "VOLUME (in3)", false, "3645(\\d{6})"),
                ApplicationIdentifier("3650", "Net volume, cubic feet (variable measure trade item)", "N4+N6", "VOLUME (ft3)", false, "3650(\\d{6})"),
                ApplicationIdentifier("3651", "Net volume, cubic feet (variable measure trade item)", "N4+N6", "VOLUME (ft3)", false, "3651(\\d{6})"),
                ApplicationIdentifier("3652", "Net volume, cubic feet (variable measure trade item)", "N4+N6", "VOLUME (ft3)", false, "3652(\\d{6})"),
                ApplicationIdentifier("3653", "Net volume, cubic feet (variable measure trade item)", "N4+N6", "VOLUME (ft3)", false, "3653(\\d{6})"),
                ApplicationIdentifier("3654", "Net volume, cubic feet (variable measure trade item)", "N4+N6", "VOLUME (ft3)", false, "3654(\\d{6})"),
                ApplicationIdentifier("3655", "Net volume, cubic feet (variable measure trade item)", "N4+N6", "VOLUME (ft3)", false, "3655(\\d{6})"),
                ApplicationIdentifier("3660", "Net volume, cubic yards (variable measure trade item)", "N4+N6", "VOLUME (yd3)", false, "3660(\\d{6})"),
                ApplicationIdentifier("3661", "Net volume, cubic yards (variable measure trade item)", "N4+N6", "VOLUME (yd3)", false, "3661(\\d{6})"),
                ApplicationIdentifier("3662", "Net volume, cubic yards (variable measure trade item)", "N4+N6", "VOLUME (yd3)", false, "3662(\\d{6})"),
                ApplicationIdentifier("3663", "Net volume, cubic yards (variable measure trade item)", "N4+N6", "VOLUME (yd3)", false, "3663(\\d{6})"),
                ApplicationIdentifier("3664", "Net volume, cubic yards (variable measure trade item)", "N4+N6", "VOLUME (yd3)", false, "3664(\\d{6})"),
                ApplicationIdentifier("3665", "Net volume, cubic yards (variable measure trade item)", "N4+N6", "VOLUME (yd3)", false, "3665(\\d{6})"),
                ApplicationIdentifier("3670", "Logistic volume, cubic inches", "N4+N6", "VOLUME (in3), log", false, "3670(\\d{6})"),
                ApplicationIdentifier("3671", "Logistic volume, cubic inches", "N4+N6", "VOLUME (in3), log", false, "3671(\\d{6})"),
                ApplicationIdentifier("3672", "Logistic volume, cubic inches", "N4+N6", "VOLUME (in3), log", false, "3672(\\d{6})"),
                ApplicationIdentifier("3673", "Logistic volume, cubic inches", "N4+N6", "VOLUME (in3), log", false, "3673(\\d{6})"),
                ApplicationIdentifier("3674", "Logistic volume, cubic inches", "N4+N6", "VOLUME (in3), log", false, "3674(\\d{6})"),
                ApplicationIdentifier("3675", "Logistic volume, cubic inches", "N4+N6", "VOLUME (in3), log", false, "3675(\\d{6})"),
                ApplicationIdentifier("3680", "Logistic volume, cubic feet", "N4+N6", "VOLUME (ft3), log", false, "3680(\\d{6})"),
                ApplicationIdentifier("3681", "Logistic volume, cubic feet", "N4+N6", "VOLUME (ft3), log", false, "3681(\\d{6})"),
                ApplicationIdentifier("3682", "Logistic volume, cubic feet", "N4+N6", "VOLUME (ft3), log", false, "3682(\\d{6})"),
                ApplicationIdentifier("3683", "Logistic volume, cubic feet", "N4+N6", "VOLUME (ft3), log", false, "3683(\\d{6})"),
                ApplicationIdentifier("3684", "Logistic volume, cubic feet", "N4+N6", "VOLUME (ft3), log", false, "3684(\\d{6})"),
                ApplicationIdentifier("3685", "Logistic volume, cubic feet", "N4+N6", "VOLUME (ft3), log", false, "3685(\\d{6})"),
                ApplicationIdentifier("3690", "Logistic volume, cubic yards", "N4+N6", "VOLUME (yd3), log", false, "3690(\\d{6})"),
                ApplicationIdentifier("3691", "Logistic volume, cubic yards", "N4+N6", "VOLUME (yd3), log", false, "3691(\\d{6})"),
                ApplicationIdentifier("3692", "Logistic volume, cubic yards", "N4+N6", "VOLUME (yd3), log", false, "3692(\\d{6})"),
                ApplicationIdentifier("3693", "Logistic volume, cubic yards", "N4+N6", "VOLUME (yd3), log", false, "3693(\\d{6})"),
                ApplicationIdentifier("3694", "Logistic volume, cubic yards", "N4+N6", "VOLUME (yd3), log", false, "3694(\\d{6})"),
                ApplicationIdentifier("3695", "Logistic volume, cubic yards", "N4+N6", "VOLUME (yd3), log", false, "3695(\\d{6})"),
                ApplicationIdentifier("37", "Count of trade items or trade item pieces contained in a logistic unit", "N2+N..8", "COUNT", true, "37(\\d{0,8})"),
                ApplicationIdentifier("3900", "Applicable amount payable or Coupon value, local currency", "N4+N..15", "AMOUNT", true, "3900(\\d{0,15})"),
                ApplicationIdentifier("3901", "Applicable amount payable or Coupon value, local currency", "N4+N..15", "AMOUNT", true, "3901(\\d{0,15})"),
                ApplicationIdentifier("3902", "Applicable amount payable or Coupon value, local currency", "N4+N..15", "AMOUNT", true, "3902(\\d{0,15})"),
                ApplicationIdentifier("3903", "Applicable amount payable or Coupon value, local currency", "N4+N..15", "AMOUNT", true, "3903(\\d{0,15})"),
                ApplicationIdentifier("3904", "Applicable amount payable or Coupon value, local currency", "N4+N..15", "AMOUNT", true, "3904(\\d{0,15})"),
                ApplicationIdentifier("3905", "Applicable amount payable or Coupon value, local currency", "N4+N..15", "AMOUNT", true, "3905(\\d{0,15})"),
                ApplicationIdentifier("3906", "Applicable amount payable or Coupon value, local currency", "N4+N..15", "AMOUNT", true, "3906(\\d{0,15})"),
                ApplicationIdentifier("3907", "Applicable amount payable or Coupon value, local currency", "N4+N..15", "AMOUNT", true, "3907(\\d{0,15})"),
                ApplicationIdentifier("3908", "Applicable amount payable or Coupon value, local currency", "N4+N..15", "AMOUNT", true, "3908(\\d{0,15})"),
                ApplicationIdentifier("3909", "Applicable amount payable or Coupon value, local currency", "N4+N..15", "AMOUNT", true, "3909(\\d{0,15})"),
                ApplicationIdentifier("3910", "Applicable amount payable with ISO currency code", "N4+N3+N..15", "AMOUNT", true, "3910(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3911", "Applicable amount payable with ISO currency code", "N4+N3+N..15", "AMOUNT", true, "3911(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3912", "Applicable amount payable with ISO currency code", "N4+N3+N..15", "AMOUNT", true, "3912(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3913", "Applicable amount payable with ISO currency code", "N4+N3+N..15", "AMOUNT", true, "3913(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3914", "Applicable amount payable with ISO currency code", "N4+N3+N..15", "AMOUNT", true, "3914(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3915", "Applicable amount payable with ISO currency code", "N4+N3+N..15", "AMOUNT", true, "3915(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3916", "Applicable amount payable with ISO currency code", "N4+N3+N..15", "AMOUNT", true, "3916(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3917", "Applicable amount payable with ISO currency code", "N4+N3+N..15", "AMOUNT", true, "3917(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3918", "Applicable amount payable with ISO currency code", "N4+N3+N..15", "AMOUNT", true, "3918(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3919", "Applicable amount payable with ISO currency code", "N4+N3+N..15", "AMOUNT", true, "3919(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3920", "Applicable amount payable, single monetary area (variable measure trade item)", "N4+N..15", "PRICE", true, "3920(\\d{0,15})"),
                ApplicationIdentifier("3921", "Applicable amount payable, single monetary area (variable measure trade item)", "N4+N..15", "PRICE", true, "3921(\\d{0,15})"),
                ApplicationIdentifier("3922", "Applicable amount payable, single monetary area (variable measure trade item)", "N4+N..15", "PRICE", true, "3922(\\d{0,15})"),
                ApplicationIdentifier("3923", "Applicable amount payable, single monetary area (variable measure trade item)", "N4+N..15", "PRICE", true, "3923(\\d{0,15})"),
                ApplicationIdentifier("3924", "Applicable amount payable, single monetary area (variable measure trade item)", "N4+N..15", "PRICE", true, "3924(\\d{0,15})"),
                ApplicationIdentifier("3925", "Applicable amount payable, single monetary area (variable measure trade item)", "N4+N..15", "PRICE", true, "3925(\\d{0,15})"),
                ApplicationIdentifier("3926", "Applicable amount payable, single monetary area (variable measure trade item)", "N4+N..15", "PRICE", true, "3926(\\d{0,15})"),
                ApplicationIdentifier("3927", "Applicable amount payable, single monetary area (variable measure trade item)", "N4+N..15", "PRICE", true, "3927(\\d{0,15})"),
                ApplicationIdentifier("3928", "Applicable amount payable, single monetary area (variable measure trade item)", "N4+N..15", "PRICE", true, "3928(\\d{0,15})"),
                ApplicationIdentifier("3929", "Applicable amount payable, single monetary area (variable measure trade item)", "N4+N..15", "PRICE", true, "3929(\\d{0,15})"),
                ApplicationIdentifier("3930", "Applicable amount payable with ISO currency code (variable measure trade item)", "N4+N3+N..15", "PRICE", true, "3930(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3931", "Applicable amount payable with ISO currency code (variable measure trade item)", "N4+N3+N..15", "PRICE", true, "3931(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3932", "Applicable amount payable with ISO currency code (variable measure trade item)", "N4+N3+N..15", "PRICE", true, "3932(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3933", "Applicable amount payable with ISO currency code (variable measure trade item)", "N4+N3+N..15", "PRICE", true, "3933(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3934", "Applicable amount payable with ISO currency code (variable measure trade item)", "N4+N3+N..15", "PRICE", true, "3934(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3935", "Applicable amount payable with ISO currency code (variable measure trade item)", "N4+N3+N..15", "PRICE", true, "3935(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3936", "Applicable amount payable with ISO currency code (variable measure trade item)", "N4+N3+N..15", "PRICE", true, "3936(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3937", "Applicable amount payable with ISO currency code (variable measure trade item)", "N4+N3+N..15", "PRICE", true, "3937(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3938", "Applicable amount payable with ISO currency code (variable measure trade item)", "N4+N3+N..15", "PRICE", true, "3938(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3939", "Applicable amount payable with ISO currency code (variable measure trade item)", "N4+N3+N..15", "PRICE", true, "3939(\\d{3})(\\d{0,15})"),
                ApplicationIdentifier("3940", "Percentage discount of a coupon", "N4+N4", "PRCNT OFF", true, "3940(\\d{4})"),
                ApplicationIdentifier("3941", "Percentage discount of a coupon", "N4+N4", "PRCNT OFF", true, "3941(\\d{4})"),
                ApplicationIdentifier("3942", "Percentage discount of a coupon", "N4+N4", "PRCNT OFF", true, "3942(\\d{4})"),
                ApplicationIdentifier("3943", "Percentage discount of a coupon", "N4+N4", "PRCNT OFF", true, "3943(\\d{4})"),
                ApplicationIdentifier("3950", "Amount Payable per unit of measure single monetary area (variable measure trade item)", "N4+N6", "PRICE/UoM", true, "3950(\\d{0,6})"),
                ApplicationIdentifier("3951", "Amount Payable per unit of measure single monetary area (variable measure trade item)", "N4+N6", "PRICE/UoM", true, "3951(\\d{0,6})"),
                ApplicationIdentifier("3952", "Amount Payable per unit of measure single monetary area (variable measure trade item)", "N4+N6", "PRICE/UoM", true, "3952(\\d{0,6})"),
                ApplicationIdentifier("3953", "Amount Payable per unit of measure single monetary area (variable measure trade item)", "N4+N6", "PRICE/UoM", true, "3953(\\d{0,6})"),
                ApplicationIdentifier("3954", "Amount Payable per unit of measure single monetary area (variable measure trade item)", "N4+N6", "PRICE/UoM", true, "3954(\\d{0,6})"),
                ApplicationIdentifier("3955", "Amount Payable per unit of measure single monetary area (variable measure trade item)", "N4+N6", "PRICE/UoM", true, "3955(\\d{0,6})"),
                ApplicationIdentifier("3956", "Amount Payable per unit of measure single monetary area (variable measure trade item)", "N4+N6", "PRICE/UoM", true, "3956(\\d{0,6})"),
                ApplicationIdentifier("3957", "Amount Payable per unit of measure single monetary area (variable measure trade item)", "N4+N6", "PRICE/UoM", true, "3957(\\d{0,6})"),
                ApplicationIdentifier("3958", "Amount Payable per unit of measure single monetary area (variable measure trade item)", "N4+N6", "PRICE/UoM", true, "3958(\\d{0,6})"),
                ApplicationIdentifier("3959", "Amount Payable per unit of measure single monetary area (variable measure trade item)", "N4+N6", "PRICE/UoM", true, "3959(\\d{0,6})"),
                ApplicationIdentifier("400", "Customers purchase order number", "N3+X..30", "ORDER NUMBER", true, "400([$charset82]{0,30})"),
                ApplicationIdentifier("401", "Global Identification Number for Consignment (GINC)", "N3+X..30", "GINC", true, "401([$charset82]{0,30})"),
                ApplicationIdentifier("402", "Global Shipment Identification Number (GSIN)", "N3+N17", "GSIN", true, "402(\\d{17})"),
                ApplicationIdentifier("403", "Routing code", "N3+X..30", "ROUTE", true, "403([$charset82]{0,30})"),
                ApplicationIdentifier("410", "Ship to - Deliver to Global Location Number", "N3+N13", "SHIP TO LOC", false, "410(\\d{13})"),
                ApplicationIdentifier("411", "Bill to - Invoice to Global Location Number", "N3+N13", "BILL TO", false, "411(\\d{13})"),
                ApplicationIdentifier("412", "Purchased from Global Location Number", "N3+N13", "PURCHASE FROM", false, "412(\\d{13})"),
                ApplicationIdentifier("413", "Ship for - Deliver for - Forward to Global Location Number", "N3+N13", "SHIP FOR LOC", false, "413(\\d{13})"),
                ApplicationIdentifier("414", "Identification of a physical location - Global Location Number", "N3+N13", "LOC No", false, "414(\\d{13})"),
                ApplicationIdentifier("415", "Global Location Number of the invoicing party", "N3+N13", "PAY TO", false, "415(\\d{13})"),
                ApplicationIdentifier("416", "GLN of the production or service location", "N3+N13", "PROD/SERV LOC", false, "416(\\d{13})"),
                ApplicationIdentifier("417", "Party GLN", "N3+N13", "PARTY", false, "417(\\d{13})"),
                ApplicationIdentifier("420", "Ship to - Deliver to postal code within a single postal authority", "N3+X..20", "SHIP TO POST", true, "420([$charset82]{0,20})"),
                ApplicationIdentifier("421", "Ship to - Deliver to postal code with ISO country code", "N3+N3+X..9", "SHIP TO POST", true, "421(\\d{3})([$charset82]{0,9})"),
                ApplicationIdentifier("422", "Country of origin of a trade item", "N3+N3", "ORIGIN", true, "422(\\d{3})"),
                ApplicationIdentifier("423", "Country of initial processing", "N3+N3+N..12", "COUNTRY - INITIAL PROCESS.", true, "423(\\d{3})(\\d{0,12})"),
                ApplicationIdentifier("424", "Country of processing", "N3+N3", "COUNTRY - PROCESS.", true, "424(\\d{3})"),
                ApplicationIdentifier("425", "Country of disassembly", "N3+N3+N..12", "COUNTRY - DISASSEMBLY", true, "425(\\d{3})(\\d{0,12})"),
                ApplicationIdentifier("426", "Country covering full process chain", "N3+N3", "COUNTRY - FULL PROCESS", true, "426(\\d{3})"),
                ApplicationIdentifier("427", "Country subdivision Of origin", "N3+X..3", "ORIGIN SUBDIVISION", true, "427([$charset82]{0,3})"),
                ApplicationIdentifier("4300", "Ship-to / Deliver-to company name", "N4+X..35", "SHIP TO COMP", true, "4300([$charset82]{0,35})"),
                ApplicationIdentifier("4301", "Ship-to / Deliver-to contact", "N4+X..35", "SHIP TO NAME", true, "4301([$charset82]{0,35})"),
                ApplicationIdentifier("4302", "Ship-to / Deliver-to address line 1", "N4+X..70", "SHIP TO ADD1", true, "4302([$charset82]{0,70})"),
                ApplicationIdentifier("4303", "Ship-to / Deliver-to address line 2", "N4+X..70", "SHIP TO ADD2", true, "4303([$charset82]{0,70})"),
                ApplicationIdentifier("4304", "Ship-to / Deliver-to suburb", "N4+X..70", "SHIP TO SUB", true, "4304([$charset82]{0,70})"),
                ApplicationIdentifier("4305", "Ship-to / Deliver-to locality", "N4+X..70", "SHIP TO LOC", true, "4305([$charset82]{0,70})"),
                ApplicationIdentifier("4306", "Ship-to / Deliver-to region", "N4+X..70", "SHIP TO REG", true, "4306([$charset82]{0,70})"),
                ApplicationIdentifier("4307", "Ship-to / Deliver-to country code", "N4+X2", "SHIP TO COUNTRY", true, "4307([A-Z]{2})"),
                ApplicationIdentifier("4308", "Ship-to / Deliver-to telephone number", "N4+X..30", "SHIP TO PHONE", true, "4308([$charset82]{0,30})"),
                ApplicationIdentifier("4310", "Return-to company name", "N4+X..35", "RTN TO COMP", true, "4310([$charset82]{0,35})"),
                ApplicationIdentifier("4311", "Return-to contact", "N4+X..35", "RTN TO NAME", true, "4311([$charset82]{0,35})"),
                ApplicationIdentifier("4312", "Return-to address line 1", "N4+X..70", "RTN TO ADD1", true, "4312([$charset82]{0,70})"),
                ApplicationIdentifier("4313", "Return-to address line 2", "N4+X..70", "RTN TO ADD2", true, "4313([$charset82]{0,70})"),
                ApplicationIdentifier("4314", "Return-to suburb", "N4+X..70", "RTN TO SUB", true, "4314([$charset82]{0,70})"),
                ApplicationIdentifier("4315", "Return-to locality", "N4+X..70", "RTN TO LOC", true, "4315([$charset82]{0,70})"),
                ApplicationIdentifier("4316", "Return-to region", "N4+X..70", "RTN TO REG", true, "4316([$charset82]{0,70})"),
                ApplicationIdentifier("4317", "Return-to country code", "N4+X2", "RTN TO COUNTRY", true, "4317([A-Z]{2})"),
                ApplicationIdentifier("4318", "Return-to postal code", "N4+X..20", "RTN TO POST", true, "4318([$charset82]{0,20})"),
                ApplicationIdentifier("4319", "Return-to telephone number", "N4+X..30", "RTN TO PHONE", true, "4319([$charset82]{0,30})"),
                ApplicationIdentifier("4320", "Service code description", "N4+X..35", "SRV DESCRIPTION", true, "4320([$charset82]{0,35})"),
                ApplicationIdentifier("4321", "Dangerous goods flag", "N4+N1", "DANGEROUS GOODS", true, "4321([01])"),
                ApplicationIdentifier("4322", "Authority to leave", "N4+N1", "AUTH TO LEAVE", true, "4322([01])"),
                ApplicationIdentifier("4323", "Signature required flag", "N4+N1", "SIG REQUIRED", true, "4323([01])"),
                ApplicationIdentifier("4324", "Not before delivery date time", "N4+N10", "NOT BEF DEL DT", true, "4324(\\d{10})"),
                ApplicationIdentifier("4325", "Not after delivery date time", "N4+N10", "NOT AFT DEL DT", true, "4325(\\d{10})"),
                ApplicationIdentifier("4326", "Release date", "N4+N6", "REL DATE", true, "4326(\\d{6})"),
                ApplicationIdentifier("7001", "NATO Stock Number (NSN)", "N4+N13", "NSN", true, "7001(\\d{13})"),
                ApplicationIdentifier("7002", "UN/ECE meat carcasses and cuts classification", "N4+X..30", "MEAT CUT", true, "7002([$charset82]{0,30})"),
                ApplicationIdentifier("7003", "Expiration date and time", "N4+N10", "EXPIRY TIME", true, "7003(\\d{10})"),
                ApplicationIdentifier("7004", "Active potency", "N4+N..4", "ACTIVE POTENCY", true, "7004(\\d{0,4})"),
                ApplicationIdentifier("7005", "Catch area", "N4+X..12", "CATCH AREA", true, "7005([$charset82]{0,12})"),
                ApplicationIdentifier("7006", "First freeze date", "N4+N6", "FIRST FREEZE DATE", true, "7006(\\d{6})"),
                ApplicationIdentifier("7007", "Harvest date", "N4+N6..12", "HARVEST DATE", true, "7007(\\d{6,12})"),
                ApplicationIdentifier("7008", "Species for fishery purposes", "N4+X..3", "AQUATIC SPECIES", true, "7008([$charset82]{0,3})"),
                ApplicationIdentifier("7009", "Fishing gear type", "N4+X..10", "FISHING GEAR TYPE", true, "7009([$charset82]{0,10})"),
                ApplicationIdentifier("7010", "Production method", "N4+X..2", "PROD METHOD", true, "7010([$charset82]{0,2})"),
                ApplicationIdentifier("7020", "Refurbishment lot ID", "N4+X..20", "REFURB LOT", true, "7020([$charset82]{0,20})"),
                ApplicationIdentifier("7021", "Functional status", "N4+X..20", "FUNC STAT", true, "7021([$charset82]{0,20})"),
                ApplicationIdentifier("7022", "Revision status", "N4+X..20", "REV STAT", true, "7022([$charset82]{0,20})"),
                ApplicationIdentifier("7023", "Global Individual Asset Identifier (GIAI) of an assembly", "N4+X..30", "GIAI - ASSEMBLY", true, "7023([$charset82]{0,30})"),
                ApplicationIdentifier("7030", "Number of processor with ISO Country Code", "N4+N3+X..27", "PROCESSOR # 0", true, "7030(\\d{3})([$charset82]{0,27})"),
                ApplicationIdentifier("7031", "Number of processor with ISO Country Code", "N4+N3+X..27", "PROCESSOR # 1", true, "7031(\\d{3})([$charset82]{0,27})"),
                ApplicationIdentifier("7032", "Number of processor with ISO Country Code", "N4+N3+X..27", "PROCESSOR # 2", true, "7032(\\d{3})([$charset82]{0,27})"),
                ApplicationIdentifier("7033", "Number of processor with ISO Country Code", "N4+N3+X..27", "PROCESSOR # 3", true, "7033(\\d{3})([$charset82]{0,27})"),
                ApplicationIdentifier("7034", "Number of processor with ISO Country Code", "N4+N3+X..27", "PROCESSOR # 4", true, "7034(\\d{3})([$charset82]{0,27})"),
                ApplicationIdentifier("7035", "Number of processor with ISO Country Code", "N4+N3+X..27", "PROCESSOR # 5", true, "7035(\\d{3})([$charset82]{0,27})"),
                ApplicationIdentifier("7036", "Number of processor with ISO Country Code", "N4+N3+X..27", "PROCESSOR # 6", true, "7036(\\d{3})([$charset82]{0,27})"),
                ApplicationIdentifier("7037", "Number of processor with ISO Country Code", "N4+N3+X..27", "PROCESSOR # 7", true, "7037(\\d{3})([$charset82]{0,27})"),
                ApplicationIdentifier("7038", "Number of processor with ISO Country Code", "N4+N3+X..27", "PROCESSOR # 8", true, "7038(\\d{3})([$charset82]{0,27})"),
                ApplicationIdentifier("7039", "Number of processor with ISO Country Code", "N4+N3+X..27", "PROCESSOR # 9", true, "7039(\\d{3})([$charset82]{0,27})"),
                ApplicationIdentifier("7040", "GS1 UIC with Extension 1 and Importer index", "N4+N1+X3", "UIC+EXT", true, "7040(\\d[$charset82]{3})"),
                ApplicationIdentifier("710", "National Healthcare Reimbursement Number (NHRN) - Germany PZN", "N3+X..20", "NHRN PZN", true, "710([$charset82]{0,20})"),
                ApplicationIdentifier("711", "National Healthcare Reimbursement Number (NHRN) - France CIP", "N3+X..20", "NHRN CIP", true, "711([$charset82]{0,20})"),
                ApplicationIdentifier("712", "National Healthcare Reimbursement Number (NHRN) - Spain CN", "N3+X..20", "NHRN CN", true, "712([$charset82]{0,20})"),
                ApplicationIdentifier("713", "National Healthcare Reimbursement Number (NHRN) - Brasil DRN", "N3+X..20", "NHRN DRN", true, "713([$charset82]{0,20})"),
                ApplicationIdentifier("714", "National Healthcare Reimbursement Number (NHRN) - Portugal AIM", "N3+X..20", "NHRN AIM", true, "714([$charset82]{0,20})"),
                ApplicationIdentifier("7230", "Certification reference", "N4+X2+X..28", "CERT #1", true, "7230([$charset82]{2,30})"),
                ApplicationIdentifier("7231", "Certification reference", "N4+X2+X..28", "CERT #2", true, "7231([$charset82]{2,30})"),
                ApplicationIdentifier("7232", "Certification reference", "N4+X2+X..28", "CERT #3", true, "7232([$charset82]{2,30})"),
                ApplicationIdentifier("7233", "Certification reference", "N4+X2+X..28", "CERT #4", true, "7233([$charset82]{2,30})"),
                ApplicationIdentifier("7234", "Certification reference", "N4+X2+X..28", "CERT #5", true, "7234([$charset82]{2,30})"),
                ApplicationIdentifier("7235", "Certification reference", "N4+X2+X..28", "CERT #6", true, "7235([$charset82]{2,30})"),
                ApplicationIdentifier("7236", "Certification reference", "N4+X2+X..28", "CERT #7", true, "7236([$charset82]{2,30})"),
                ApplicationIdentifier("7237", "Certification reference", "N4+X2+X..28", "CERT #8", true, "7237([$charset82]{2,30})"),
                ApplicationIdentifier("7238", "Certification reference", "N4+X2+X..28", "CERT #9", true, "7238([$charset82]{2,30})"),
                ApplicationIdentifier("7239", "Certification reference", "N4+X2+X..28", "CERT #10", true, "7239([$charset82]{2,30})"),
                ApplicationIdentifier("7240", "Protocol ID", "N4+X..20", "PROTOCOL", true, "7240([$charset82]{0,20})"),
                ApplicationIdentifier("8001", "Roll products (width, length, core diameter, direction, splices)", "N4+N14", "DIMENSIONS", true, "8001(\\d{14})"),
                ApplicationIdentifier("8002", "Cellular mobile telephone identifier", "N4+X..20", "CMT No", true, "8002([$charset82]{0,20})"),
                ApplicationIdentifier("8003", "Global Returnable Asset Identifier (GRAI)", "N4+N14+X..16", "GRAI", true, "8003(\\d{14})([$charset82]{0,16})"),
                ApplicationIdentifier("8004", "Global Individual Asset Identifier (GIAI)", "N4+X..30", "GIAI", true, "8004([$charset82]{0,30})"),
                ApplicationIdentifier("8005", "Price per unit of measure", "N4+N6", "PRICE PER UNIT", true, "8005(\\d{6})"),
                ApplicationIdentifier("8006", "Identification of an individual trade item piece", "N4+N14+N2+N2", "ITIP", true, "8006(\\d{14})(\\d{2})(\\d{2})"),
                ApplicationIdentifier("8007", "International Bank Account Number (IBAN)", "N4+X..34", "IBAN", true, "8007([$charset82]{0,34})"),
                ApplicationIdentifier("8008", "Date and time of production", "N4+N8+N..4", "PROD TIME", true, "8008(\\d{8})(\\d{0,4})"),
                ApplicationIdentifier("8009", "Optically Readable Sensor Indicator", "N4+X..50", "OPTSEN", true, "8009([$charset82]{0,50})"),
                ApplicationIdentifier("8010", "Component/Part Identifier (CPID)", "N4+Y..30", "CPID", true, "8010([$charset39]{0,30})"),
                ApplicationIdentifier("8011", "Component/Part Identifier serial number (CPID SERIAL)", "N4+N..12", "CPID SERIAL", true, "8011(\\d{0,12})"),
                ApplicationIdentifier("8012", "Software version", "N4+X..20", "VERSION", true, "8012([$charset82]{0,20})"),
                ApplicationIdentifier("8013", "Global Model Number (GMN)", "N4+X..30", "GMN (for medical devices, the default, global data title is BUDI-DI)", true, "8013([$charset82]{0,30})"),
                ApplicationIdentifier("8017", "Global Service Relation Number to identify the relationship between an organisation offering services and the provider of services", "N4+N18", "GSRN - PROVIDER", true, "8017(\\d{18})"),
                ApplicationIdentifier("8018", "Global Service Relation Number to identify the relationship between an organisation offering services and the recipient of services", "N4+N18", "GSRN - RECIPIENT", true, "8018(\\d{18})"),
                ApplicationIdentifier("8019", "Service Relation Instance Number (SRIN)", "N4+N..10", "SRIN", true, "8019(\\d{0,10})"),
                ApplicationIdentifier("8020", "Payment slip reference number", "N4+X..25", "REF No", true, "8020([$charset82]{0,25})"),
                ApplicationIdentifier("8026", "Identification of pieces of a trade item (ITIP) contained in a logistic unit", "N4+N14+N2+N2", "ITIP CONTENT", true, "8026(\\d{14})(\\d{2})(\\d{2})"),
                ApplicationIdentifier("8110", "Coupon code identification for use in North America", "N4+X..70", "", true, "8110([$charset82]{0,70})"),
                ApplicationIdentifier("8111", "Loyalty points of a coupon", "N4+N4", "POINTS", true, "8111(\\d{4})"),
                ApplicationIdentifier("8112", "Paperless coupon code identification for use in North America", "N4+X..70", "", true, "8112([$charset82]{0,70})"),
                ApplicationIdentifier("8200", "Extended Packaging URL", "N4+X..70", "PRODUCT URL", true, "8200([$charset82]{0,70})"),
                ApplicationIdentifier("90", "Information mutually agreed between trading partners", "N2+X..30", "INTERNAL", true, "90([$charset82]{0,30})"),
                ApplicationIdentifier("91", "Company internal information", "N2+X..90", "INTERNAL", true, "91([$charset82]{0,90})"),
                ApplicationIdentifier("92", "Company internal information", "N2+X..90", "INTERNAL", true, "92([$charset82]{0,90})"),
                ApplicationIdentifier("93", "Company internal information", "N2+X..90", "INTERNAL", true, "93([$charset82]{0,90})"),
                ApplicationIdentifier("94", "Company internal information", "N2+X..90", "INTERNAL", true, "94([$charset82]{0,90})"),
                ApplicationIdentifier("95", "Company internal information", "N2+X..90", "INTERNAL", true, "95([$charset82]{0,90})"),
                ApplicationIdentifier("96", "Company internal information", "N2+X..90", "INTERNAL", true, "96([$charset82]{0,90})"),
                ApplicationIdentifier("97", "Company internal information", "N2+X..90", "INTERNAL", true, "97([$charset82]{0,90})"),
                ApplicationIdentifier("98", "Company internal information", "N2+X..90", "INTERNAL", true, "98([$charset82]{0,90})"),
                ApplicationIdentifier("99", "Company internal information", "N2+X..90", "INTERNAL", true, "99([$charset82]{0,90})")
        )

        private val prefixMap = generatePrefixMap()

        private fun generatePrefixMap() : Map<String, ArrayList<ApplicationIdentifier>> {
            val map = HashMap<String, ArrayList<ApplicationIdentifier>>()
            allIdentifiers.forEach {
                val list = map.getOrPut(it.twoDigitIdentifier, { ArrayList() })
                list.add(it)
            }
            return map
        }

        /**
        * Get the application identifier by its prefix
        */
        fun byPrefix(prefix: String): List<ApplicationIdentifier>? {
            return prefixMap[prefix]
        }

        /**
        * Get the length of the application identifier contents
        */
        fun elementLength(prefix: String): Int {
            return predefinedLengths[prefix] ?: 0
        }
    }
}

