site_name: Snabble Android SDK
site_url: https://snabble.github.io/Android-SDK/
theme:
  logo: logo.svg
  name: material
  custom_dir: overrides
  features:
    - content.code.annotate
    - content.code.annotate
    - navigation.tabs
  palette:
    primary: white
extra_css:
  - snabble.css
repo_name: Android-SDK
repo_url: https://github.com/snabble/Android-SDK
plugins:
  - codeinclude
  - macros
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
nav:
  - Home: index.md
  - Changelog: changelog.md
  - API:
    - Overview: android-api.md
    - Core: api/core/index.md
    - Firebase Detector: api/firebase-detector/index.md
    - UI: api/ui/index.md
    - UI integration: api/ui-integration/index.md
    - Utils: api/utils/index.md
  - News: https://snabble.io/en/latest/
  - Stores: https://snabble.io/en/stores/
  - Careers: https://snabble.io/en/jobs/
  - Contact: https://snabble.io/en/contact/
extra:
  sdk_version: '0.51.3'