site_name: Snabble Android SDK
theme:
  logo: logo.svg
  name: material
  custom_dir: overrides
  features:
    - content.code.annotate
    - navigation.tabs # move first navigation level to tabs
  palette:
    primary: white
extra_css:
  - snabble.css
repo_name: Android-SDK
repo_url: https://github.com/snabble/Android-SDK
plugins:
  - codeinclude
markdown_extensions:
  - pymdownx.tabbed
nav:
  - Home: index.md
  - Changelog: ../CHANGELOG.md
  - API: api/index.md
  - News: https://snabble.io/en/latest/
  - Stores: https://snabble.io/en/stores/
  - Careers: https://snabble.io/en/jobs/
  - Contact: https://snabble.io/en/contact/