name: Build

on:
  push:
    branches: [ main, master, feature/documentation ] # TODO remove the feature branch
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Build
        # TODO Roll this back to build and move Deploy docs to publish.yml
        run: ./gradlew build dokkaGfmMultiModule
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@nomaterial
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: docs/mkdocs.yml
          REQUIREMENTS: docs/requirements.txt