name: Publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Build
        run: ./gradlew build
      - name: Generate documentation
        run: ./gradlew dokkaHtmlMultiModule && sed -E 's/^## \[([^[]+)\]$/## \1/g' CHANGELOG.md | sed -E 's/^### (.+)$/**\1**\n/g' | sed -E 's/All notable changes to this project will be documented in this file./All notable changes of the Android SDK are noted in this document./' > docs/changelog.md
      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: docs