name: Publish

on:
  release:
    types: [ published ]
  workflow_dispatch:

env:
  SDK_VERSION_NAME: ${{ github.ref_name }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [ self-hosted, android ]

    steps:
      - name: Build
        run: ./gradlew build
      - name: Publish to Maven Repository
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "${{ secrets.MAVEN_DEPLOY }}"
          ./github_release.sh
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository
      - name: Generate documentation
        run: ./gradlew dokkaHtmlMultiModule
      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: docs
