name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Build
        run: ./gradlew build
      - name: Publish to Maven Repository
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "${{ secrets.MAVEN_DEPLOY }}"
          ./github_release.sh
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository
      - name: Generate documentation
        run: ./gradlew dokkaGfmMultiModule && sed -E 's/^## \[([^[]+)\]$/## \1/g' CHANGELOG.md | sed -E 's/^### (.+)$/**\1**\n/g' | sed -E 's/All notable changes to this project will be documented in this file./All notable changes of the Android SDK are noted in this document./' > docs/docs/changelog.md
      - name: Deploy documentation
        uses: mhausenblas/mkdocs-deploy-gh-pages@nomaterial
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: docs/mkdocs.yml
          REQUIREMENTS: docs/requirements.txt
